### ISSUE TITLE
Xây dựng chi tiết UI của dashboard

### ISSUE THREAD

**Issue by duyNguyen8202** [sy-nt/Dashboard_Group11#17]
- [x] Chia layout
- [x] Tạo trang hiển thị list dataSample (Id, name)
- [x] Chức năng search
- [x] Chức năng filter
- [x] Tạo trang hiển thị list Item của dataSample
- [x] Tạo model show chart
- [x] Tạo component hiển thị chart

**Comment by sy-nt** [comment]
Task 1: https://docs.google.com/document/d/1zyrJObL5lvTLnXPcz-zxxDduGSlMxHTECZ_Kf2ecO7A/edit?usp=sharing
Task 2: https://docs.google.com/document/d/1rCoGgWecdGxDCgxk4HXSKtD0RGdyFydjkNUPQLIzoWg/edit?usp=sharing
Task 3: https://docs.google.com/document/d/18vKo5RfwzFO-NM48rQQkQnvQf1cX2wAtU2h47SK_FwQ/edit?usp=sharing
Task 4: https://docs.google.com/document/d/1h62lg_4HyeSlPbO5e1l-OSiOgN7wWJLpUWz_wMq_XoU/edit?usp=sharing
Task 5: https://docs.google.com/document/d/1HWWvHZoghIX92Odl1JC_DVGnr3CcInkHIjW-NfYtzaI/edit?usp=sharing
Task 6: https://docs.google.com/document/d/1N4bkDa0vF6VqpsXprQaAz4xWCNG03KXuEYxOgK1Y12w/edit?usp=sharing
Task 7: https://docs.google.com/document/d/1-2sFyAtvQHPbK1TN3mAHTlclHBiRvSfkiKpDBlvz62g/edit?usp=sharing
