### ISSUE TITLE
Viết sơ thảo về chức năng

### ISSUE THREAD

**Issue by duyNguyen8202** [sy-nt/Dashboard_Group11#2]
- [ ] Viết sơ thảo về chức năng.
- [ ] Chọn lựa các công nghệ sử dụng

**Comment by lptnhan2002ute** [comment]
https://docs.google.com/document/d/1UpZJm4aFJESydJwhj2E0MF6JRBS90Pcu5B_RZL3kDMk/edit?usp=sharing
