### ISSUE TITLE
Lựa chọn ngôn ngữ và framework

### ISSUE THREAD

**Issue by duyNguyen8202** [sy-nt/Dashboard_Group11#4]

**Comment by duyNguyen8202** [comment]
- [ ] Lua chon framework

- [ ] Khai quat ve framework

- [ ] Cach cai dat

**Comment by sy-nt** [comment]
Do dữ liệu trả về là 1 object chứa rất nhiều giá trị và số liệu. Do đó để dễ dàng sử lý dữ liệu thì mình dùng python.
Với cả python thì các thành viên trong nhóm đều đã từng biết qua nên sử dụng python trong project này là lựa chọn hợp lý.
Bên cạnh đó thì mình sẽ sử dụng Flask để tiến hành code. Flask được biết tới như là một Framework nhẹ, ít phụ thuộc vào các cập nhật và dễ tìm kiếm các lỗi bảo mật.
Mình đồng thời có thể chạy trên docker lẫn local. Và cài đặt thư viện của python bằng những câu lệnh đơn giản như pip install Flask hoặc conda install Flask
